### ISSUE TITLE
Menus generate invalid HTML, missing </li> tags

### ISSUE THREAD

**Issue by clabland** [ktsashes/FruitJS#24]
* Create test.md markdown page:
```md
#Test page
```
* Create manifest.json for test.md:
```json
{
	"pages": ["test.md"]
}
```
* Run fruitjs manifest.json
* Examine HTML output of index.html:
```html
		<section id="navigation">
			<h1><a href="index.html">Docs</a></h1>
			<nav>
					<li><a href="index.html#im-a-test">Im a test</a>
			</nav>
		</section>
```

**Comment by clabland** [comment]
Found in version 0.6.4: https://www.npmjs.com/package/fruitjs

**Comment by ktsashes** [comment]
`</li>` is not necessary in certain circumstances (like within a `<nav>` element). Closing tags are assumed as of HTML5. Same goes for certain cases with the `</p>` tag as well which I believe may also be omitted sometimes

**Comment by ktsashes** [comment]
>  The end tag can be omitted if it is immediately followed by another <li> element or if there is no more content in its parent element.

From [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li?redirectlocale=en-US&redirectslug=HTML%2FElement%2Fli)

**Comment by clabland** [comment]
It's still invalid according to the validator, though not for the reason I mentioned:

Element li not allowed as child of element nav in this context. (Suppressing further errors from this subtree.)
					<li><a href="index.html#im-a-test">Im a test</a>
Contexts in which element li may be used:
Inside ol elements.
Inside ul elements.
Inside menu elements whose type attribute is in the toolbar state.

**Comment by ktsashes** [comment]
Gah! They changed that in the spec again?! :(

Filed as bug #25 and I'll take a look and get it fixed. Shouldn't be difficult.

**Comment by clabland** [comment]
:+1:
